# Generated by Django 5.2.6 on 2025-09-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("time_minutes", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(max_length=1000)),
                ("ingredients", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="RecipeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
