# Generated by Django 5.2.6 on 2025-09-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Рецепт", "verbose_name_plural": "Рецепты"},
        ),
        migrations.AlterModelOptions(
            name="recipecomment",
            options={
                "verbose_name": "Коммент к рецепту",
                "verbose_name_plural": "Комменты к рецептам",
            },
        ),
        migrations.AlterField(
            model_name="recipecomment",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="recipe.recipe",
            ),
        ),
    ]
