# Generated by Django 5.2.6 on 2025-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(verbose_name="Название")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                ("customer_name", models.CharField(verbose_name="Имя заказчика")),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Еmail заказчика"),
                ),
                ("status", models.CharField(verbose_name="Статус")),
                ("created_at", models.CharField(verbose_name="Создан")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
